# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/docker/build/controller/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/docker/build/pulsar/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/src/frontend/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/dashboard/"
    schedule:
      interval: "daily"
