version: '3.9'
services:
  controller:
    image: controller
    build:
      context: docker/build/controller
      dockerfile: Dockerfile
    entrypoint: ['bash', 'controller_entrypoint.sh']
    env_file:
      - token.env
    environment:
      WAIT_HOSTS: redis:6379
    volumes:
      - ./private_key:/private_key
      - ./public_key:/public_key
      - ./token:/token
      - ./src/controller/app.py:/workspace/app.py
      - ./src/controller/keys_create.py:/workspace/keys_create.py
      - ./docker/entrypoint/controller_entrypoint.sh:/workspace/controller_entrypoint.sh
      - ./docker/entrypoint/:/entrypoint/  # for cross-platform wait
    expose: # nop, documentation only
      - "8000"
    depends_on:
      - redis
  
  pulsar:
    image: pulsar # with httpx for functions worker
    build:
      context: docker/build/pulsar
      dockerfile: Dockerfile
    entrypoint: ['bash', 'pulsar_entrypoint.sh']
    env_file:
      - api.env
    volumes:
      - ./public_key:/public_key
      - ./token:/token
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
      - ./conf/standalone.conf:/pulsar/conf/standalone.conf # real conf
      - ./conf/broker.conf:/pulsar/conf/broker.conf # only for further deployment
      - ./conf/client.conf:/pulsar/conf/client.conf
      - ./conf/functions_worker.yml:/pulsar/conf/functions_worker.yml
      - ./src/tagger/tagger.py:/pulsar/tagger.py
      - ./docker/entrypoint/pulsar_entrypoint.sh:/pulsar/pulsar_entrypoint.sh
      - ./docker/entrypoint/functions_create.sh:/pulsar/functions_create.sh
      - ./logs:/pulsar/logs
    expose: # nop, documentation only
      - "6650"
      - "8080"
    depends_on:
      - controller
  
  dashboard:
    image: dashboard
    build:
      context: docker/build/dashboard
      dockerfile: Dockerfile
    entrypoint: ['bash', 'dashboard_entrypoint.sh']
    env_file:
      - token.env
    environment:
      DEBUG: 1
      WAIT_HOSTS: redis:6379
    volumes:
      - ./src/dashboard:/workspace/dashboard
      - ./docker/entrypoint/dashboard_entrypoint.sh:/workspace/dashboard_entrypoint.sh
      - ./docker/entrypoint/:/entrypoint/  # for cross-platform wait
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:5.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password # todo: add into env files
    volumes:
      - mongodata:/data/db
    expose: # nop, documentation only
      - "27017"

  redis:
    image: redis:6.2.6-alpine3.15

  nginx:
    build:
      context: .
      dockerfile: docker/build/nginx/Dockerfile
      args:
        GITHUB_SHA: ${GITHUB_SHA:-UNKNOWN}
    ports:
      - "8000:8000"
    depends_on:
      - controller
      - pulsar
      - dashboard

volumes: 
  pulsardata: {}
  pulsarconf: {}
  mongodata: {}
