version: '3.9'
services:
  # TODO: reverse proxy
  controller:
    image: controller
    build:
      context: controller_image
      dockerfile: Dockerfile
    entrypoint: ['python', 'app.py']
    volumes:
      - ./controller:/workspace
    ports:
      - '8000:8000'
    networks:
      - intra
  
  pulsar:
    image: pulsar # with aiohttp for functions worker
    build:
      context: pulsar_image
      dockerfile: Dockerfile
    entrypoint: ['bash', 'pulsar_entrypoint.sh']
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
      - ./logs:/pulsar/logs
      - ./conf/broker.conf:/pulsar/conf/broker.conf
      - ./entrypoint/pulsar_entrypoint.sh:/pulsar/pulsar_entrypoint.sh
      - ./entrypoint/functions_create.sh:/pulsar/functions_create.sh
      - ./tagger/tagger.py:/pulsar/tagger.py
    ports:
      - '8080:8080'
      - '6650:6650'
    networks:
      - intra

volumes: 
  pulsardata: {}
  pulsarconf: {}
networks:
  intra:
    driver: bridge