version: '3.9'
services:
  # TODO: reverse proxy
  controller:
    image: controller
    build: 
      context: controller_image
      dockerfile: Dockerfile
    entrypoint: ['node', 'app/app.js']
    volumes:
      - ./controller:/workspace/app
    ports:
      - '8000:8000'
    networks:
      - intra
  
  pulsar:
    image: apachepulsar/pulsar:2.8.1
    entrypoint: ['bin/pulsar', 'standalone']
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    ports:
      - '8080:8080'
      - '6650:6650'
    networks:
      - intra

volumes: 
  pulsardata: {}
  pulsarconf: {}
networks:
  intra:
    driver: bridge