name: Deploy to development server
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Grab the deploy secret key
        env:
          id_ed25519: ${{ secrets.DEPLOY_ROOT_PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          echo $id_ed25519 | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Add to known hosts
        run: |
          ssh-keyscan 152.136.181.192 > ~/.ssh/known_hosts
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Fetch the repository on dev machine
        run: |
          ssh root@152.136.181.192 "cd /srv/DanmakuIt && git fetch --all && git reset --hard origin/master"
      - name: Rebuild
        run: |
          ssh root@152.136.181.192 "cd /srv/DanmakuIt && docker-compose build"
      - name: Fire up the new server # build again in case of previous error...
        run: |
          ssh root@152.136.181.192 "cd /srv/DanmakuIt && docker-compose down && docker-compose up --build"
