name: Publish docs

on:
  push:
    branches: [ docs ]
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'
        cache-dependency-path: ./docs/yarn.lock
    - name: Install dependencies for docs
      working-directory: ./docs
      run: yarn install --frozen-lockfile
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.9
    - name: Cache for Python
      uses: actions/cache@v2
      with:
        path: ~/src/dashboard/.venv
        key: ${{ runner.os }}-poetry-venv-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies for FastAPI
      working-directory: ./src/dashboard/
      run: |
        pip install --user poetry
        poetry config virtualenvs.in-project true
        poetry install
    - name: Generate OpenAPI for dashboard
      working-directory: ./docs
      run: yarn docs:openapi
    - name: Build docs
      working-directory: ./docs
      run: yarn docs:build
    - name: Write Commit Hash
      working-directory: ./docs/.vitepress/dist
      run: mkdir commit; echo success > ./commit/$GITHUB_SHA
    - uses: actions/upload-artifact@master
      with:
        name: github-pages
        path: ./docs/.vitepress/dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/download-artifact@master
      with:
        name: github-pages
        path: "."
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: "."

  crawl:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    - uses: actions/checkout@v2
    - name: Wait on
      uses: iFaxity/wait-on-action@v1
      with:
        resource:
          https-get: https://blog.panda2134.site/DanmakuIt/commit/${{ github.sha }}
        delay: 60000
    - name: Algolia Docsearch Indexer
      uses: darrenjennings/algolia-docsearch-action@v0.2.0
      with:
        algolia_application_id: 623XG0125Y
        algolia_api_key:  ${{ secrets.ALGOLIA_API_KEY }}
        file: ./docs/algolia.json